name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Build and Push"]  # run after Docker image is built & pushed
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/zaimshukran/tui-assessment:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:8080 ghcr.io/${{ github.repository }}:latest