name: Java CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check -Dnvd.api.key=${{ secrets.NVD_API_KEY }} -Ddependency-check.failBuildOnCVSS=7

      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.3.0:check -Dspotbugs.html.output=true

      - name: Run Tests with Coverage
        run: mvn clean verify

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=zaimshukran_TUI-Assessment

      - name: Upload analysis reports
        uses: actions/upload-artifact@v4
        with:
          name: maven-reports
          path: |
            **/target/site/**
            **/target/spotbugs.html
            **/target/spotbugsXml.xml
            **/target/checkstyle-result.xml
            **/target/jacoco/**
            **/target/dependency-check-report.html
          retention-days: 7
